changesetBaseRefs:
  - main
  - HEAD

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  '@metriport/api-sdk@*':
    dependencies:
      http-status: '*'

yarnPath: .yarn/releases/yarn-4.5.3.cjs
