apiVersion: v1
kind: Service
metadata:
  name: extensions-nodeport
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080 # choose a free port on your nodes
  selector:
    app: extensions