import {
  type DataPointDefinition,
  type Webhook,
} from '@awell-health/extensions-core'

const dataPoints = {
  eventType: {
    key: 'eventType',
    valueType: 'string',
  },
  hello: {
    key: 'webhookDataPoint',
    valueType: 'string',
  },
  a_string: {
    key: 'a_string',
    valueType: 'string',
  },
  a_number: {
    key: 'a_number',
    valueType: 'number',
  },
  a_boolean: {
    key: 'a_boolean',
    valueType: 'boolean',
  },
  a_date: {
    key: 'a_date',
    valueType: 'date',
  },
  a_phone: {
    key: 'a_phone',
    valueType: 'telephone',
  },
  a_json: {
    key: 'a_json',
    valueType: 'json',
  },
} satisfies Record<string, DataPointDefinition>

// Payload must be exported so it can be included in the declaration file generated by the build script
export interface Payload {
  eventType: string
  hello: string
  a_string: string
  a_number: number
  a_boolean: boolean
  a_date: string
  a_phone: string
  a_json: string
}

export const demo: Webhook<keyof typeof dataPoints, Payload> = {
  key: 'demo',
  dataPoints,
  onWebhookReceived: async ({ payload }, onSuccess, onError) => {
    const {
      eventType,
      hello,
      a_string,
      a_number,
      a_boolean,
      a_date,
      a_phone,
      a_json,
    } = payload
    await onSuccess({
      data_points: {
        eventType,
        hello,
        a_string,
        a_number: String(a_number),
        a_boolean: String(a_boolean),
        a_date,
        a_phone,
        a_json, // objects unique come already serialized as a string
      },
    })
  },
}

// Unnecessary, but included to help with type inference and consistency
export type Demo = typeof demo
