import {
  FieldType,
  NumericIdSchema,
  type Field,
} from '@awell-health/extensions-core'
import z, { type ZodTypeAny } from 'zod'

export const fields = {
  patientId: {
    id: 'patientId',
    label: 'Patient ID',
    description: 'The patient for whom the the history is being created',
    type: FieldType.NUMERIC,
    required: true,
  },
  practiceId: {
    id: 'practiceId',
    label: 'Practice ID',
    description:
      'Practice ID where the vitas are beind measured for the patient',
    type: FieldType.NUMERIC,
    required: true,
  },
  visitNoteId: {
    id: 'visitNoteId',
    label: 'Visit Note ID',
    description: 'Will only allow unsigned visit notes',
    type: FieldType.NUMERIC,
    required: false,
  },
  nonVisitNoteId: {
    id: 'nonVisitNoteId',
    label: 'Non-Visit Note ID',
    description: 'Will only allow unsigned non-visit notes',
    type: FieldType.NUMERIC,
    required: false,
  },
  bmi: {
    id: 'bmi',
    label: 'BMI',
    description:
      'Body Mass Index; optional and calculated if height and weight are available',
    type: FieldType.NUMERIC,
    required: false,
  },
  height: {
    id: 'height',
    label: 'Height',
    description: 'Patient height in inches',
    type: FieldType.STRING,
    required: false,
  },
  heightNote: {
    id: 'height note',
    label: 'Height Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
  weight: {
    id: 'weight',
    label: 'Weight',
    description: 'Patient weight in lbs',
    type: FieldType.STRING,
    required: false,
  },
  weightNote: {
    id: 'weightNote',
    label: 'Weight Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
  oxygen: {
    id: 'oxygen',
    label: 'Oxygen',
    description: 'Oxygen',
    type: FieldType.STRING,
    required: false,
  },
  oxygenNote: {
    id: 'oxygenNote',
    label: 'Oxygen Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
  rr: {
    id: 'rr',
    label: 'Respiratory Rate',
    description: 'Respiratory rate',
    type: FieldType.STRING,
    required: false,
  },
  rrNote: {
    id: 'rrNote',
    label: 'Respiratory Rate Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
  hr: {
    id: 'hr',
    label: 'Heart Rate',
    description: 'Heart rate',
    type: FieldType.STRING,
    required: false,
  },
  hrNote: {
    id: 'hrNote',
    label: 'Heart Rate Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
  hc: {
    id: 'hc',
    label: 'Head Circumference',
    description: 'Head circumference',
    type: FieldType.STRING,
    required: false,
  },
  hcNote: {
    id: 'hcNote',
    label: 'Head Circumference Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
  temperature: {
    id: 'temperature',
    label: 'Temperature',
    description: 'Temperature',
    type: FieldType.STRING,
    required: false,
  },
  temperatureNote: {
    id: 'temperatureNote',
    label: 'Temperature Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
  bp: {
    id: 'bp',
    label: 'Blood Pressure',
    description: 'Blood pressure',
    type: FieldType.STRING,
    required: false,
  },
  bpNote: {
    id: 'bpNote',
    label: 'Blood Pressure Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
  bodyfat: {
    id: 'bodyfat',
    label: 'Body Fat',
    description: 'Body fat percentage',
    type: FieldType.STRING,
    required: false,
  },
  bodyfatNote: {
    id: 'bodyfatNote',
    label: 'Body Fat Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
  dlm: {
    id: 'dlm',
    label: 'Dry Lean Mass',
    description: 'Dry lean mass',
    type: FieldType.STRING,
    required: false,
  },
  dlmNote: {
    id: 'dlmNote',
    label: 'Dry Lean Mass Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
  bfm: {
    id: 'bfm',
    label: 'Body Fat Mass',
    description: 'Body fat mass',
    type: FieldType.STRING,
    required: false,
  },
  bfmNote: {
    id: 'bfmNote',
    label: 'Body Fat Mass Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
  wc: {
    id: 'wc',
    label: 'Waist Circumference',
    description: 'Waist circumference',
    type: FieldType.STRING,
    required: false,
  },
  wcNote: {
    id: 'wcNote',
    label: 'Waist Circumference Note',
    description: '',
    type: FieldType.STRING,
    required: false,
  },
} satisfies Record<string, Field>

export const FieldsValidationSchema = z.object({
  patientId: NumericIdSchema,
  practiceId: NumericIdSchema,
  visitNoteId: NumericIdSchema.optional(),
  nonVisitNoteId: NumericIdSchema.optional(),
  bmi: z.number().optional(),
  height: z.string().optional(),
  heightNote: z.string().optional(),
  weight: z.string().optional(),
  weightNote: z.string().optional(),
  oxygen: z.string().optional(),
  oxygenNote: z.string().optional(),
  rr: z.string().optional(),
  rrNote: z.string().optional(),
  hr: z.string().optional(),
  hrNote: z.string().optional(),
  hc: z.string().optional(),
  hcNote: z.string().optional(),
  temperature: z.string().optional(),
  temperatureNote: z.string().optional(),
  bp: z.string().optional(),
  bpNote: z.string().optional(),
  bodyfat: z.string().optional(),
  bodyfatNote: z.string().optional(),
  dlm: z.string().optional(),
  dlmNote: z.string().optional(),
  bfm: z.string().optional(),
  bfmNote: z.string().optional(),
  wc: z.string().optional(),
  wcNote: z.string().optional(),
} satisfies Record<keyof typeof fields, ZodTypeAny>)
