import { NumericIdSchema } from '@awell-health/extensions-core'
import { z } from 'zod'
import { specialtySchema } from './specialty.zod'

export const AuthorizationForSchema = z.enum([
  'Referral For Treatment, includes Consult Visit',
  'Procedure / Testing Only',
  'Consult (One Visit Only)',
] as const)

export const AuthorizationForShortSchema = z.enum([
  'ForTreat',
  'ProcOnly',
  'ConsOnly',
] as const)

export const ResolutionStateSchema = z.enum([
  'outstanding',
  'fulfilled',
  'cancelled',
] as const)

export const resolutionSchema = z.object({
  id: z.number(),
  document: z.number(),
  resolving_document: z.number().nullable(),
  state: ResolutionStateSchema,
  note: z.string().nullable(),
  created_date: z.string().datetime(), // Validates ISO datetime strings
  deleted_date: z.string().datetime().nullable(),
})

export const icdCodesSchema = z.array(
  z.object({
    code: z.string(),
    description: z.string(),
  }),
)

// Note: id is not included in the schema as it's generated by the server
// It's only included in the response type (PostReferralOrderResponse)
export const referralOrderSchema = z.object({
  authorization_for: AuthorizationForSchema,
  auth_number: z.string().nullable(),
  consultant_name: z.string(),
  short_consultant_name: z.string().optional(),
  date_for_reEval: z.string().datetime().nullable(),
  authorization_for_short: AuthorizationForShortSchema.nullable().optional(),
  practice: NumericIdSchema,
  patient: NumericIdSchema,
  letter: NumericIdSchema,
  resolution: resolutionSchema.nullable(),
  icd10_codes: icdCodesSchema.optional(),
  specialty: specialtySchema.nullable(),
})
