import { z, type ZodTypeAny } from 'zod'
import { type Field, FieldType } from '@awell-health/extensions-core'

export const fields = {
  addend_01: {
    id: 'addend_01',
    label: 'Addend',
    description: '',
    required: true,
    type: FieldType.NUMERIC,
  },
  addend_02: {
    id: 'addend_02',
    label: 'Addend',
    description: '',
    required: true,
    type: FieldType.NUMERIC,
  },
  addend_03: {
    id: 'addend_03',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_04: {
    id: 'addend_04',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_05: {
    id: 'addend_05',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_06: {
    id: 'addend_06',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_07: {
    id: 'addend_07',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_08: {
    id: 'addend_08',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_09: {
    id: 'addend_09',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_10: {
    id: 'addend_10',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_11: {
    id: 'addend_11',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_12: {
    id: 'addend_12',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_13: {
    id: 'addend_13',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_14: {
    id: 'addend_14',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_15: {
    id: 'addend_15',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_16: {
    id: 'addend_16',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_17: {
    id: 'addend_17',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_18: {
    id: 'addend_18',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_19: {
    id: 'addend_19',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
  addend_20: {
    id: 'addend_20',
    label: 'Addend',
    description: '',
    required: false,
    type: FieldType.NUMERIC,
  },
} satisfies Record<string, Field>

export const FieldsValidationSchema = z.object({
  addend_01: z.number(),
  addend_02: z.number(),
  addend_03: z.number().optional(),
  addend_04: z.number().optional(),
  addend_05: z.number().optional(),
  addend_06: z.number().optional(),
  addend_07: z.number().optional(),
  addend_08: z.number().optional(),
  addend_09: z.number().optional(),
  addend_10: z.number().optional(),
  addend_11: z.number().optional(),
  addend_12: z.number().optional(),
  addend_13: z.number().optional(),
  addend_14: z.number().optional(),
  addend_15: z.number().optional(),
  addend_16: z.number().optional(),
  addend_17: z.number().optional(),
  addend_18: z.number().optional(),
  addend_19: z.number().optional(),
  addend_20: z.number().optional(),
} satisfies Record<keyof typeof fields, ZodTypeAny>)
