import { type AxiosResponse } from 'axios'
import { type PatientResponse } from '../../../types'
import { type DeepPartial } from '../../../../../src/lib/types'

export const CreatePatientSuccessMock = {
  status: 200,
  statusText: 'OK',
  data: {
    id: 142857632874497,
    actual_name: null,
    address: null,
    caregiver_practice: 141127173275652,
    consents: [],
    created_date: '2025-04-01T09:48:38Z',
    deleted_date: null,
    deleted_insurances: [],
    dob: '1993-11-30',
    emails: [],
    emergency_contact: null,
    employer: null,
    ethnicity: 'No ethnicity specified',
    first_name: 'Nick Test',
    gender_identity: 'unknown',
    guarantor: null,
    insurances: [],
    last_name: 'Test',
    legal_gender_marker: null,
    master_patient: null,
    merged_into_chart: null,
    metadata: null,
    middle_name: '',
    notes: null,
    patient_status: {
      deceased_date: null,
      inactive_reason: null,
      last_status_change: '2025-04-01T09:48:39Z',
      notes: null,
      status: 'active',
    },
    phones: [],
    preference: null,
    preferred_language: null,
    preferred_service_location: null,
    previous_first_name: null,
    previous_last_name: null,
    primary_care_provider: null,
    primary_care_provider_npi: null,
    primary_physician: 141377681883138,
    pronouns: null,
    race: 'No race specified',
    sex: 'Male',
    sexual_orientation: 'unknown',
    ssn: null,
    tags: [],
    vip: false,
  },
} satisfies DeepPartial<AxiosResponse<PatientResponse>>
