import { type AxiosResponse } from 'axios'
import { type GetContactResponseType } from '../../../lib/api/schema/GetContact.schema'

export const GetContactResponseMock = {
  data: {
    active: false,
    address: '18 Test St.',
    description: null,
    email: 'testing@joinbetter.com',
    id: 1,
    job_title: null,
    language: 'en',
    mobile: null,
    name: 'Test Test',
    phone: null,
    time_zone: 'Pacific Time (US & Canada)',
    twitter_id: null,
    custom_fields: {
      order_issue: null,
      primary_insurance: null,
      peer_support_coach: null,
      documentation_owner: null,
      freshsales_lead_owner: 'Nick H',
      partnership_name: null,
      access_restrictions: null,
      patient_time_zone: null,
      betterhealthuserid: null,
    },
    tags: [],
    other_emails: [],
    facebook_id: null,
    created_at: '2024-01-10T21:51:54Z',
    updated_at: '2024-03-12T21:34:31Z',
    csat_rating: null,
    preferred_source: 'phone',
    company_id: null,
    view_all_tickets: null,
    other_companies: [],
    unique_external_id: null,
    twitter_profile_status: false,
    twitter_followers_count: null,
    avatar: null,
  },
} satisfies Partial<AxiosResponse<GetContactResponseType>>
