export enum Category {
  COMMUNICATION = 'Communication',
  INTEGRATIONS = 'Integrations',
  DOCUMENT_MANAGEMENT = 'Document Management',
  CONTENT_AND_FILES = 'Content & Files',
  WORKFLOW = 'Workflow',
  MATH = 'Math',
  SCHEDULING = 'Scheduling',
  DATA = 'Data',
  BILLING = 'Billing',
  MEDICINE_MANAGEMENT = 'Medicine Management',
  DEMO = 'Demo',
  FORMS = 'Forms',
  AI = 'Artificial Intelligence (AI)',
}
