export const mockFormDefinitionResponse = {
  form: {
    questions: [
      {
        options: [],
        key: 'typePChildrenTextThankYouForConsideringAReferralToTextPalomaHealthBoldTrueTextForYourPatientsAutismSpectrumDisorderAsdAssessmentTypePChildrenTextBeforeWeProceedWeKindlyAskThatYouCompleteAShortSurveyApproximatelyText1015MinutesBoldTrueTextToProvideEssentialInformationAboutThePatientsMedicalHistoryAndSymptomsThisWillEnsureAThoroughAndAccurateAssessmentTypePChildrenTextExclusionCriteriaBoldTrueTextNPleaseNoteThatWeAreUnableToAcceptReferralsForTypeUlChildrenTypeLiChildrenTypeLicChildrenTextPatientsUnder18TypeLiChildrenTypeLicChildrenTextPatientsCurrentlyReceivingInPersonCareElsewhereTypeLiChildrenTypeLicChildrenTextPatientsWithConditionsThatMayMimicAsdSymptomsEGUntreatedHearingOrVisionIssuesTypePChildrenTextTypePChildrenTextWeAppreciateYourTimeAndLookForwardToCollaboratingToProvideTheBestPossibleCare',
        id: 'icNVBlttsN8h',
        definition_id: 'YqDiAtSb7kRv',
        title:
          '<p class="slate-p">Thank you for considering a referral to <strong class="slate-bold">Paloma Health</strong> for your patient’s autism spectrum disorder (ASD) assessment.</p><p class="slate-p">Before we proceed, we kindly ask that you complete a short survey (approximately <strong class="slate-bold">10-15 minutes</strong>) to provide essential information about the patient’s medical history and symptoms. This will ensure a thorough and accurate assessment.</p><p class="slate-p"><strong class="slate-bold">Exclusion Criteria</strong>:<br/>Please note that we are unable to accept referrals for:</p><ul class="slate-ul"><li class="slate-li"><div style="position:relative">Patients under 18</div></li><li class="slate-li"><div style="position:relative">Patients currently receiving in-person care elsewhere</div></li><li class="slate-li"><div style="position:relative">Patients with conditions that may mimic ASD symptoms (e.g., untreated hearing or vision issues)</div></li></ul><p class="slate-p"></p><p class="slate-p">We appreciate your time and look forward to collaborating to provide the best possible care.</p>',
        dataPointValueType: null,
        questionType: 'NO_INPUT',
        userQuestionType: 'DESCRIPTION',
        metadata: null,
        __typename: 'Question',
      },
      {
        options: [],
        key: 'PATIENT_FN',
        id: 'PSpxniOv52vQ',
        definition_id: '4kLSm6MPL4RO',
        title: "What's the patient's first name?",
        dataPointValueType: 'STRING',
        questionType: 'INPUT',
        userQuestionType: 'SHORT_TEXT',
        metadata: '{"healthieCustomModuleId": "14460375"}',
        __typename: 'Question',
      },
      {
        options: [],
        key: 'PATIENT_LN',
        id: 'ABOb9suU2dMc',
        definition_id: 'R9EjG3z4Yi3H',
        title: "What's the patient's last name?",
        dataPointValueType: 'STRING',
        questionType: 'INPUT',
        userQuestionType: 'SHORT_TEXT',
        metadata: '{"healthieCustomModuleId": "14460376"}',
        __typename: 'Question',
      },
      {
        options: [],
        key: 'PATIENT_NHS_NUMBER',
        id: 'R85tp6Ib9eYp',
        definition_id: '1nzbEWbQvWzH',
        title: "Please provide the patient's NHS Number:",
        dataPointValueType: 'NUMBER',
        questionType: 'INPUT',
        userQuestionType: 'NUMBER',
        metadata: '{"healthieCustomModuleId": "14460377"}',
        __typename: 'Question',
      },
      {
        options: [],
        key: 'PATIENT_DOB',
        id: 'Olf3pPSHc512',
        definition_id: 'O3nGKwmD1nFo',
        title: "What's the patient's date of birth?",
        dataPointValueType: 'DATE',
        questionType: 'INPUT',
        userQuestionType: 'DATE',
        metadata: '{"healthieCustomModuleId": "14460378"}',
        __typename: 'Question',
      },
      {
        id: '7ulbRDEEy6Yj',
        title: 'How often do you have a drink containing alcohol?',
        dataPointValueType: 'NUMBER',
        options: [
          {
            id: 'DARgGXXdk7H4',
            value: 0,
            value_string: '0',
            label: 'Never',
            __typename: 'Option',
          },
          {
            id: '8S8SbjUp4B0j',
            value: 1,
            value_string: '1',
            label: 'Monthly or less',
            __typename: 'Option',
          },
          {
            id: 'LASgrQvw8cJH',
            value: 2,
            value_string: '2',
            label: '2-4 times a months',
            __typename: 'Option',
          },
          {
            id: 'Qlkv1mwj1ISc',
            value: 3,
            value_string: '3',
            label: '2-3 times a week',
            __typename: 'Option',
          },
          {
            id: 'oSEMLNQX34F1',
            value: 4,
            value_string: '4',
            label: '4 or more times a week',
            __typename: 'Option',
          },
        ],
        questionType: 'MULTIPLE_CHOICE',
        userQuestionType: 'MULTIPLE_CHOICE',
        questionConfig: {
          recode_enabled: false,
          use_select: false,
          mandatory: false,
          slider: null,
          phone: null,
          number: null,
          multiple_select: null,
          date: null,
          __typename: 'QuestionConfig',
        },
        __typename: 'Question',
      },
    ],
  },
}
