export const mockFormDefinitionResponse = {
  form: {
    title: 'General Dummy Form',
    questions: [
      {
        id: 'description',
        definition_id: 'rUfECkXAtCxe',
        title:
          '<p class="slate-p">This is a description question. It&#x27;s doesn&#x27;t collect any data but just shows some text to the user.</p>',
        key: 'typePChildrenTextThisIsADescriptionQuestionItsDoesntCollectAnyDataButJustShowsSomeTextToTheUser',
        dataPointValueType: null,
        questionType: 'NO_INPUT',
        userQuestionType: 'DESCRIPTION',
        metadata: JSON.stringify({ healthieCustomModuleId: 'description' }),
        options: [],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'single_select_number',
        definition_id: 'UPHy_BJdHhzs',
        title: 'Single select (number)',
        key: 'singleSelectNumber',
        dataPointValueType: 'NUMBER',
        questionType: 'MULTIPLE_CHOICE',
        userQuestionType: 'MULTIPLE_CHOICE',
        metadata: JSON.stringify({
          healthieCustomModuleId: 'single_select_number',
        }),
        options: [
          {
            id: 'zOTvuy0usHkb',
            value: 0,
            value_string: '0',
            label: 'Option 1',
            __typename: 'Option',
          },
          {
            id: 'q6jRNHKATieI',
            value: 1,
            value_string: '1',
            label: 'Option 2',
            __typename: 'Option',
          },
          {
            id: 'vvMBtwpHl0o5',
            value: 2,
            value_string: '2',
            label: 'Option 3',
            __typename: 'Option',
          },
        ],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'single_select_string',
        definition_id: 'KjYHPz9kZLlnvguMT3epw',
        title: 'Single select (string)',
        key: 'singleSelectString',
        dataPointValueType: 'STRING',
        questionType: 'MULTIPLE_CHOICE',
        userQuestionType: 'MULTIPLE_CHOICE',
        metadata: JSON.stringify({
          healthieCustomModuleId: 'single_select_string',
        }),
        options: [
          {
            id: 'u9qpd6kPr83f',
            value: -1,
            value_string: 'option_1',
            label: 'Option 1',
            __typename: 'Option',
          },
          {
            id: 'yRy_LwI1refh',
            value: -1,
            value_string: 'option_2',
            label: 'Option 2',
            __typename: 'Option',
          },
          {
            id: 'OOCTmiXXvjpN',
            value: -1,
            value_string: 'option_3',
            label: 'Option 3',
            __typename: 'Option',
          },
        ],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'multi_select_number',
        definition_id: 'y8dZyIh1JEHo',
        title: 'Multiple select (number)',
        key: 'multipleSelectNumber',
        dataPointValueType: 'NUMBERS_ARRAY',
        questionType: 'MULTIPLE_CHOICE',
        userQuestionType: 'MULTIPLE_SELECT',
        metadata: JSON.stringify({
          healthieCustomModuleId: 'multi_select_number',
        }),
        options: [
          {
            id: 'NRhfKVrRJ1qQ',
            value: 0,
            value_string: '0',
            label: 'Option 1',
            __typename: 'Option',
          },
          {
            id: 'kbdbxrZP9-cY',
            value: 1,
            value_string: '1',
            label: 'Option 2',
            __typename: 'Option',
          },
          {
            id: '7EFDVDtvyZ6h',
            value: 2,
            value_string: '2',
            label: 'Option 3',
            __typename: 'Option',
          },
        ],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'multi_select_string',
        definition_id: 'KYcDSScnM8cxu2WMyVuIi',
        title: 'Multiple select (string)',
        key: 'multipleSelectString',
        dataPointValueType: 'STRINGS_ARRAY',
        questionType: 'MULTIPLE_CHOICE',
        userQuestionType: 'MULTIPLE_SELECT',
        metadata: JSON.stringify({
          healthieCustomModuleId: 'multi_select_string',
        }),
        options: [
          {
            id: 'v3XJP3ZgMyc9',
            value: -1,
            value_string: 'option_1',
            label: 'Option 1',
            __typename: 'Option',
          },
          {
            id: 'JYHA_c6UFLJX',
            value: 3232,
            value_string: 'option_2',
            label: 'Option 2',
            __typename: 'Option',
          },
          {
            id: 'xmXV065kgDEk',
            value: -1,
            value_string: 'option_3',
            label: 'Option 3',
            __typename: 'Option',
          },
        ],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'yes_no',
        definition_id: 'QSzAEHWU5SNl',
        title: 'Yes or no? (boolean)',
        key: 'yesOrNoBoolean',
        dataPointValueType: 'BOOLEAN',
        questionType: 'INPUT',
        userQuestionType: 'YES_NO',
        metadata: JSON.stringify({ healthieCustomModuleId: 'yes_no' }),
        options: [],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'slider',
        definition_id: 'qeIf6jhiizCu',
        title: 'Slider',
        key: 'slider',
        dataPointValueType: 'NUMBER',
        questionType: 'INPUT',
        userQuestionType: 'SLIDER',
        metadata: JSON.stringify({ healthieCustomModuleId: 'slider' }),
        options: [],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'date',
        definition_id: 'yX86ygNm5M0a',
        title: 'Date',
        key: 'date',
        dataPointValueType: 'DATE',
        questionType: 'INPUT',
        userQuestionType: 'DATE',
        metadata: JSON.stringify({ healthieCustomModuleId: 'date' }),
        options: [],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'email',
        definition_id: 'PKp3cBu5lPvR',
        title: 'Email',
        key: 'email',
        dataPointValueType: 'STRING',
        questionType: 'INPUT',
        userQuestionType: 'EMAIL',
        metadata: JSON.stringify({ healthieCustomModuleId: 'email' }),
        options: [],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'number',
        definition_id: '0NuSKClQNXV_',
        title: 'Question that collects a numeric value',
        key: 'questionThatCollectsANumericValue',
        dataPointValueType: 'NUMBER',
        questionType: 'INPUT',
        userQuestionType: 'NUMBER',
        metadata: JSON.stringify({ healthieCustomModuleId: 'number' }),
        options: [],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'short_text',
        definition_id: 'qiIFXlNLUVzN',
        title: 'Question that collects a sstring value',
        key: 'questionThatCollectsASstringValue',
        dataPointValueType: 'STRING',
        questionType: 'INPUT',
        userQuestionType: 'SHORT_TEXT',
        metadata: JSON.stringify({ healthieCustomModuleId: 'short_text' }),
        options: [],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'long_text',
        definition_id: 'tSFHKGROz6Zm',
        title: 'Question that collects a string but long-form (textarea)',
        key: 'questionThatCollectsAStringButLongFormTextarea',
        dataPointValueType: 'STRING',
        questionType: 'INPUT',
        userQuestionType: 'LONG_TEXT',
        metadata: JSON.stringify({ healthieCustomModuleId: 'long_text' }),
        options: [],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
      {
        id: 'phone',
        definition_id: 'yZahm5RhM1mb',
        title: 'Question that collects a phone number',
        key: 'questionThatCollectsAPhoneNumber',
        dataPointValueType: 'TELEPHONE',
        questionType: 'INPUT',
        userQuestionType: 'TELEPHONE',
        metadata: JSON.stringify({ healthieCustomModuleId: 'phone' }),
        options: [],
        __typename: 'Question',
        questionConfig: null,
        rule: null,
      },
    ],
  },
}
