import { type AxiosResponse } from 'axios'

export const CreateSMSBroadcastMockResponse = {
  status: 200,
  statusText: 'OK',
  headers: {
    Location: 'https://staging-rest.call-em-all.com/v1/broadcasts',
  },
  data: {
    Uri: '/v1/broadcasts/10006607',
    UriBroadcastDetails: '/v1/broadcasts/10006607/details',
    BroadcastID: 10006607,
    BroadcastName: 'testBroadcast',
    BroadcastType: 'SMS',
    BroadcastStatus: 'AuthorizationApproved',
    BroadcastStatusCategory: 'Scheduled',
    CreatedDate: '2020-11-20 14:04:09-0600',
    StartDate: '2025-01-02 13:15:00-0000',
    CompletedDate: null,
    TextNumberID: '2142960678',
    TextMessage: 'This is a test text message. Please reply.',
    CreditsUsed: null,
    MaxCreditCost: 1,
    PhoneNumberCount: 1,
    TotalCompleted: 0,
    User: {
      PinCode: null,
      UserID: 215790,
      UserName: null,
      FirstName: null,
      LastName: null,
      Email: null,
      Phone: null,
      CallerID: null,
      IsMasterUser: false,
      AuthToken: null,
      State: null,
      Permissions: null,
    },
    RetryTimes: 1,
    CallThrottle: 0,
    LivePersonTotal: 0,
    AnsweringMachineTotal: 0,
    BusyNoAnswerTotal: 0,
    InvalidNumberTotal: 0,
    SurveyResponseTotal: 0,
    TransferTotal: 0,
    SurveyResponses: null,
    MaxMessageLength: 30,
    MessageRecordingInstruction: null,
    EstimatedDuration: 0,
    EstimatedCompletion: null,
    ExcludedDaysIgnored: false,
    CallingWindowIgnored: false,
    NotEnoughTimeToComplete: false,
  },
} satisfies Partial<AxiosResponse>
