import {
  type Form,
  QuestionType,
  DataPointValueType,
  UserQuestionType,
} from '../../../../../extensions/awell/v1/gql/graphql'

export const formDefinitionMock: Form = {
  id: 'Z-N6CVFy9cv-',
  definition_id: 'q6OwH0yp2JKq',
  title: 'Form with all question types',
  release_id: 'gGENPAtSM5j4-K7yFHzdl',
  key: 'formWithAllQuestionTypes',
  metadata: '{"form": "metadata"}',
  trademark: null,
  questions: [
    {
      id: 'MUha7ldV6gJL',
      definition_id: 'rUfECkXAtCxe',
      title:
        '<p class="slate-p">This is a description question. It&#x27;s doesn&#x27;t collect any data but just shows some text to the user.</p>',
      key: 'typePChildrenTextThisIsADescriptionQuestionItsDoesntCollectAnyDataButJustShowsSomeTextToTheUser',
      dataPointValueType: null,
      questionType: QuestionType.NoInput,
      userQuestionType: UserQuestionType.Description,
      metadata: null,
      options: [],
      rule: null,
    },
    {
      id: 'bVGD5I6ckKZx',
      definition_id: 'UPHy_BJdHhzs',
      title: 'Single select (number)',
      key: 'singleSelectNumber',
      dataPointValueType: DataPointValueType.Number,
      questionType: QuestionType.MultipleChoice,
      userQuestionType: UserQuestionType.MultipleChoice,
      metadata: '{"meta": "data"}',
      options: [
        {
          id: 'zOTvuy0usHkb',
          value: 0,
          value_string: '0',
          label: 'Option 1',
        },
        {
          id: 'q6jRNHKATieI',
          value: 1,
          value_string: '1',
          label: 'Option 2',
        },
        {
          id: 'vvMBtwpHl0o5',
          value: 2,
          value_string: '2',
          label: 'Option 3',
        },
      ],
      rule: null,
    },
    {
      id: 'KcvNZ5dJHPf0',
      definition_id: '5rmKlZdZGCxK',
      title: 'Single select (string)',
      key: 'singleSelectString',
      dataPointValueType: DataPointValueType.String,
      questionType: QuestionType.MultipleChoice,
      userQuestionType: UserQuestionType.MultipleChoice,
      metadata: null,
      options: [
        {
          id: 'u9qpd6kPr83f',
          value: -1,
          value_string: 'option_1',
          label: 'Option 1',
        },
        {
          id: 'yRy_LwI1refh',
          value: -1,
          value_string: 'option_2',
          label: 'Option 2',
        },
        {
          id: 'OOCTmiXXvjpN',
          value: -1,
          value_string: 'option_3',
          label: 'Option 3',
        },
        {
          id: 'P32BtMUeLwNN',
          value: -1,
          value_string: 'option_4',
          label: 'helloo',
        },
        {
          id: 'rrgEixvMsF9I',
          value: -1,
          value_string: 'option_5',
          label: 'helloooooo',
        },
        {
          id: 'seZqcRQb2qDm',
          value: -1,
          value_string: 'option_6',
          label: 'test',
        },
      ],
    },
    {
      id: 'saf_RczvRbay',
      definition_id: 'y8dZyIh1JEHo',
      title: 'Multiple select (number)',
      key: 'multipleSelectNumber',
      dataPointValueType: DataPointValueType.NumbersArray,
      questionType: QuestionType.MultipleChoice,
      userQuestionType: UserQuestionType.MultipleSelect,
      metadata: null,
      options: [
        {
          id: 'NRhfKVrRJ1qQ',
          value: 0,
          value_string: '0',
          label: 'Option 1',
        },
        {
          id: 'kbdbxrZP9-cY',
          value: 1,
          value_string: '1',
          label: 'Option 2',
        },
        {
          id: '7EFDVDtvyZ6h',
          value: 2,
          value_string: '2',
          label: 'Option 3',
        },
        {
          id: 'CKqrKwhPbObE',
          value: 3,
          value_string: '3',
          label: 'Option 4',
        },
      ],
      rule: null,
    },
    {
      id: 'knDhobvb9xWJ',
      definition_id: 'PZJCzbhg0Ygr',
      title: 'Multiple select (string)',
      key: 'multipleSelectString',
      dataPointValueType: DataPointValueType.StringsArray,
      questionType: QuestionType.MultipleChoice,
      userQuestionType: UserQuestionType.MultipleSelect,
      metadata: null,
      options: [
        {
          id: 'v3XJP3ZgMyc9',
          value: -1,
          value_string: 'some option',
          label: 'Option 1',
        },
        {
          id: 'JYHA_c6UFLJX',
          value: 3232,
          value_string: '3232',
          label: 'Option 2',
        },
        {
          id: 'xmXV065kgDEk',
          value: -1,
          value_string: 'another option',
          label: 'Option 3',
        },
        {
          id: 'eCrmxno3fpcy',
          value: -1,
          value_string: 'option 4',
          label: 'fdsfds',
        },
      ],
    },
    {
      id: '-hCGgfqR3zZ7',
      definition_id: 'QSzAEHWU5SNl',
      title: 'Yes or no? (boolean)',
      key: 'yesOrNoBoolean',
      dataPointValueType: DataPointValueType.Boolean,
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.YesNo,
      metadata: null,
      options: [],
      rule: null,
    },
    {
      id: 'yiVk87BHUNYs',
      definition_id: 'qeIf6jhiizCu',
      title: 'Slider',
      key: 'slider',
      dataPointValueType: DataPointValueType.Number,
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Slider,
      metadata: null,
      options: [],
      rule: null,
    },
    {
      id: 'ypR9Yudhfsbg',
      definition_id: 'yX86ygNm5M0a',
      title: 'Date',
      key: 'date',
      dataPointValueType: DataPointValueType.Date,
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Date,
      metadata: null,
      options: [],
      rule: null,
    },
    {
      id: 'C9dHRQWojfkP',
      definition_id: '0NuSKClQNXV_',
      title: 'Question that collects a numeric value',
      key: 'questionThatCollectsANumericValue',
      dataPointValueType: DataPointValueType.Number,
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Number,
      metadata: null,
      options: [],
      rule: null,
    },
    {
      id: 'vn-VF15nIsv_',
      definition_id: 'qiIFXlNLUVzN',
      title: 'Question that collects a sstring value',
      key: 'questionThatCollectsASstringValue',
      dataPointValueType: DataPointValueType.String,
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.ShortText,
      metadata: null,
      options: [],
      rule: null,
    },
    {
      id: 'PwQq1MVz3sYn',
      definition_id: 'tSFHKGROz6Zm',
      title: 'Question that collects a string but long-form (textarea)',
      key: 'questionThatCollectsAStringButLongFormTextarea',
      dataPointValueType: DataPointValueType.String,
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.LongText,
      metadata: null,
      options: [],
      rule: null,
    },
    {
      id: 'uuir17H9iz9P',
      definition_id: 'yZahm5RhM1mb',
      title: 'Question that collects a phone number',
      key: 'questionThatCollectsAPhoneNumber',
      dataPointValueType: DataPointValueType.Telephone,
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Telephone,
      metadata: null,
      options: [],
      rule: null,
    },
  ],
}
