name: Auto Assign on Label

on:
  pull_request:
    types: [labeled]

jobs:
  auto-assign:
    if: ${{ github.event.label.name == 'ai-actions' }}
    runs-on: ubuntu-latest
    steps:
      - name: Assign AI Engineer to production AI Actions PRs
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          assignees: belmai
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
